apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: blazing
resources:
  - namespace.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml

helmCharts:
  - name: postgresql
    namespace: blazing
    releaseName: postgresql
    repo: https://charts.bitnami.com/bitnami
    version: 16.1.2
    valuesFile: values.yaml
